# Generated by Django 6.0.1 on 2026-01-12 14:56

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin_safira').exists():
        User.objects.create(
            username='admin_safira',
            password=make_password('safiradmin'),
            is_superuser=True,
            is_staff=True,
            first_name='Safira',
            last_name='Admin',
            email='safira@safiracloud.com'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
